#!perl -wl
use Mac::Glue;
use strict;

my($vol, $f, $volume, $label, $position, $oldpos);

($vol = MacPerl::MakePath(scalar MacPerl::Volumes)) =~ s/:$//;

$f          = new Mac::Glue 'Finder';
$position   = $f->p('position', item => $vol);
$label      = $f->p('label_index',  item => $vol);
$oldpos     = $f->get($position)->get;

$f->activate;
$f->set($position, {to => [10, 10]});

for (0 .. 2**5) {
    $f->set($label, {to => $_});
}

$f->set($position, {to => $oldpos});

$f->beep(3);
