#!perl -wl
use Mac::Glue;
use Mac::Apps::Launch;
$p = new Mac::Glue 'PreFab Player';

LaunchApps(['ttxt'], 1);  # simple text

$p->do_menu_menu_item('New',        { of_menu => 'File' });
$p->type('This land is your land, this land is my land.');
$p->do_menu_menu_item('Select All', { of_menu => 'Edit' });
$p->do_menu_menu_item('Replace',    { of_menu => 'Edit' });
$p->type("your\tmy");
$p->type('L');  # enter
