#!perl -w
use strict;
use Mac::Glue;
use Mac::Files;
use Mac::InternetConfig;

my $file = FindFolder(kOnSystemDisk, kDesktopFolderType) . ":gluenotes.pod";
my $map  = $InternetConfigMap{$file};
#FSpCreate($file, $map->file_creator, $map->file_type) or die $^E;

my $url = new Mac::Glue 'URL_Access_Scripting';
$url->activate;
$url->download('http://pudge.net/macperl/gluenotes.pod',
  { to => $file, progress => 1});
$url->quit;
